// Generated by Xata Codegen 0.26.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "post-meta",
    columns: [{ name: "views", type: "int", notNull: true, defaultValue: "0" }],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type PostMeta = InferredTypes["post-meta"];
export type PostMetaRecord = PostMeta & XataRecord;

export type DatabaseSchema = {
  "post-meta": PostMetaRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Viktor-Malmedal-s-workspace-qgrnqc.eu-central-1.xata.sh/db/malmedal-dev",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
